name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install Node dependencies and build
      run: |
        npm ci
        npm audit fix
        npm run build
        
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy Hostinger via rsync
      run: |
        ssh-keyscan -p ${{ secrets.HOSTINGER_PORT }} ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts
        rsync -av --delete \
          --exclude='.env' \
          --exclude='storage/' \
          -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.HOSTINGER_PORT }}" \
          ./ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_PATH }}

    - name: Run migrations and seed
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        key: ${{ secrets.HOSTINGER_KEY }}
        port: ${{ secrets.HOSTINGER_PORT }}
        verbose: true
        script: |
          cd ${{ secrets.HOSTINGER_PATH }}
          /opt/alt/php84/usr/bin/php artisan migrate:fresh --seed --force
          /opt/alt/php84/usr/bin/php artisan cache:clear
          /opt/alt/php84/usr/bin/php artisan config:cache
          /opt/alt/php84/usr/bin/php artisan route:cache
